#!/bin/bash

cd "$1"

jq -n \
    --arg description "$(cat description.md)" \
    --arg starter "$(cat starter.py)" \
    --argfile meta meta.json \
    --argfile io io.json \
    '{
        starter: $starter,
        description: $description,
        meta: $meta,
        io: $io,
    }' \
    > problem.json
