// THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.

import eat_outside from './eat-outside/problem.json';
import intersecting_metro from './intersecting-metro/problem.json';
const problems = [
    eat_outside,
    intersecting_metro,
];
export default problems;
